#!/bin/bash -l

#the "-l" in bash setting is necessary to indicate login shell (it also must be on top of the script)s
#ulimit command sets the output limit to zerro, so that none of the spitted out error text will be recorded. This is to avoid filling up scratch under an unexpected error load 
#the first 2 modules change the compiler to gcc
#the 3rd module loads gsl compatible with selected gsl version
#the 4th module loads openblas, so that lapack will work 
#the 5th&6th modules are necessary to use ublas. 5th is blas itself, and it depends on pyhton hence 7th)

ulimit -c 0
module unload compilers mpi mkl
module load compilers/gnu/4.9.2
module load gsl/1.16/gnu-4.9.2 
module load openblas/0.2.14/gnu-4.9.2
module load python/2.7.9
module load boost/1_54_0/gnu-4.9.2

#the path settings are necessary for pardiso
#the OMP_NUM_THREADS is necessary for setting the maximum number of parallel threads
#the OPENBLAS_NUM_THREADS is necessary for setting the thread # of openBLAS separately.
#   the linked library is not compatible with openMP, if this env var is not set, it creates warning messages 
#   for each call to an openBLAS function. 
export PATH=/home/ucbpnkh/LocalLibs/:$PATH
export LD_LIBRARY_PATH=/home/ucbpnkh/LocalLibs/:$LD_LIBRARY_PATH
export LIBRARY_PATH=/home/ucbpnkh/LocalLibs/:$LIBRARY_PATH
export OMP_NUM_THREADS=4
export OPENBLAS_NUM_THREADS=1
rm /home/ucbpnkh/Scratch/bulkruns/Run07007/Out
rm /home/ucbpnkh/Scratch/bulkruns/Run07007/Save*
rm /home/ucbpnkh/Scratch/bulkruns/Run07007/tmp 
rm /home/ucbpnkh/Scratch/bulkruns/Run07007/cont/Out
rm /home/ucbpnkh/Scratch/bulkruns/Run07007/cont/Save*

/home/ucbpnkh/Scratch/bin/TissueFolding -mode SimulationOnTheGo -i /home/ucbpnkh/Scratch/bulkruns/ModelInputs/modelinput07007 -od /home/ucbpnkh/Scratch/bulkruns/Run07007/ > /home/ucbpnkh/Scratch/bulkruns/Run07007/tmp
