# Workflow to build executables in the TissueFolding pipeline and run regression tests on them

name: Build and Regression Tests for Mesh Generation

# Set to run on pull requests and pushes to ARCCollaboration or to master directly
on:
  push:
    branches: ["master", "ARCCollaboration"]
  pull_request:
    branches: ["master", "ARCCollaboration"]

jobs:
  # Build mesh generation executable and run regression tests on it
  mesh_generation_build_and_test:
    name: Mesh Generation - Build and Regression Tests
    runs-on: ubuntu-latest
    steps:
      # check out the repository
      - name: Check out repository
        uses: actions/checkout@v3
      
      # update apt
      - name: Update apt
        run: |
          sudo apt-get update
  
      # Begin attempts to build EllipseFromOutline
      # Install triangle dependency
      - name: Install triangle
        run: |
          sudo apt-get install triangle-bin
      
      # Install EllipseFromOutline using CMake instructions
      - name: Build EllipseFromOutline
        run: |
          cd ${{ github.workspace }}/ToolBox/MeshGeneration/2DEllipse/src
          mkdir build
          cd build
          cmake ..
          cmake --build .
      
      # Relocate EllipseFromOutline to expected folder for runs
      - name: Relocate EllipseFromOutline
        run: |
          mv ${{ github.workspace }}/ToolBox/MeshGeneration/2DEllipse/src/build/EllipseFromOutline ${{ github.workspace }}/ToolBox/MeshGeneration/2DEllipse/
  
      # Run regression tests for mesh generation
      # Install test dependencies
      - name: Install test dependencies
        run: |
          sudo apt-get install python3
          pip install pytest
      
      # Run pytest in the tests/mesh_gen_reg directory
      - name: Run mesh generation regression tests
        run: |
          cd ${{ github.workspace }}/tests/mesh_gen_reg/
          pytest
  
  # Build TissueFolding without pardiso and run regression checks
  TissueFolding_no_Pardiso:
    name: TissueFolding (no Pardiso) - Build and Regression Tests
    runs-on: ubuntu-latest
    steps:
      # check out repository
      - name: Check out repository
        uses: actions/checkout@v3
      
      # Install build dependencies
      # GitHub ubuntu-latest runners have preinstalled: g++ gcc gfortran libgsl-dev
      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libopenblas-dev libboost-all-dev
      
      # Build TissueFolding using the CMake instructions
      - name: Build TissueFolding
        run: |
          cd ${{ github.workspace }}/TissueFolding/SourceCode/
          mkdir build
          cd build
          cmake ..
          cmake --build .
      
      # Move TissueFolding to the expected directory for testing
      - name: Move TissueFolding
        run: |
          mv ${{ github.workspace }}/TissueFolding/SourceCode/build/TissueFolding ${{ github.workspace }}/TissueFolding/
      
      # Run regression tests for non-Pardiso simulation
      # Install test dependencies
      - name: Install test dependencies
        run: |
          sudo apt-get install python3
          pip install pytest
      
      # Run pytest in the tests/sim_no_pardiso_reg/ directory
      - name: Run TissueFolding (non-Pardiso) regression tests
        run: |
          cd ${{ github.workspace }}/tests/sim_no_pardiso_reg/
          pytest