# Workflow to build EllipseFromOutline (mesh generation executable) and place it into the correct directory.

name: Build EllipseFromOutline

# Set to run on pull requests, pushes to master/ ARCCollaboration directly, and if requested on GitHub
on:
  push:
    branches: ["master", "ARCCollaboration"]
  pull_request:
    branches: ["master", "ARCCollaboration"]
  workflow_dispatch:

jobs:
  # Build mesh generation executable
  build_EllipseFromOutline:
    
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      # Install the triangle dependency
      - name: Install triangle
        run: |
          sudo apt-get update
          sudo apt-get install triangle-bin

      # Install using the CMake instructions
      - name: Build EllipseFromOutline
        run: |
          cd ${{ github.workspace}}/ToolBox/MeshGeneration/2DEllipse/src
          mkdir build
          cd build
          cmake ..
          cmake --build .
