# Workflow to build executables in the TissueFolding pipeline and run regression tests on them

name: Build and Regression Tests

# Set to run on pull requests and pushes to ARCCollaboration or to master directly
on:
  push:
    branches: ["master", "ARCCollaboration"]
  pull_request:
    branches: ["master", "ARCCollaboration"]

jobs:
  # check out repository
  checkout_repository:
    name: checkout repository
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      
      - name: Update apt
        run: |
          sudo apt-get update
  
  # attempt to build EllipseFromOutline
  build_EllipseFromOutline:
    name: build EllipseFromOutline
    runs-on: ubuntu-latest
    needs: checkout_repository
    steps:
      # Install triangle dependency
      - name: Install triangle
        run: |
          sudo apt-get install triangle-bin
      
      # Install EllipseFromOutline using CMake instructions
      - name: Build EllipseFromOutline
        run: |
          ls
          cd ${{ github.workspace }}/ToolBox/MeshGeneration/2DEllipse/src
          mkdir build
          cd build
          cmake ..
          cmake --build .
      
      # Relocate EllipseFromOutline to expected folder for runs
      - name: Relocate EllipseFromOutline
        run: |
          mv ${{ github.workspace }}/ToolBox/MeshGeneration/2DEllipse/src/build/EllipseFromOutline ${{ github.workspace }}/ToolBox/MeshGeneration/2DEllipse/
  
  # Run regression tests for mesh generation
  mesh_generation_regression_tests:
    name: Regression Tests - Mesh Generation
    needs: build_EllipseFromOutline
    runs-on: ubuntu-latest
    steps:
      # Install test dependencies
      - name: Install test dependencies
        run: |
          sudo apt-get install python3
          pip install pytest
      
      # Run pytest in the tests/mesh_gen_reg directory
      - name: Run mesh generation regression tests
        run: |
          cd ${{ github.workspace }}/tests/mesh_gen_reg/
          pytest