# Workflow to perform regression tests

name: Mesh Generation Regression Tests

# Workflow will run on pull requests, pushes to master directly, and if requested through the dispatch on Github
on:
  # Triggers the workflow on pull request events, or direct pushes to the "master" branch
  push:
    branches: ["master", "ARCCollaboration"]
  pull_request:
    branches: ["master", "ARCCollaboration"]
  workflow_dispatch:

jobs:
  # Run regression tests
  regression_tests:

    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      # Install the triangle dependency
      - name: Install triangle
        run: |
          sudo apt-get update
          sudo apt-get install triangle-bin

      # Install using the CMake instructions
      - name: Build EllipseFromOutline
        run: |
          cd ${{ github.workspace }}/ToolBox/MeshGeneration/2DEllipse/src
          mkdir build
          cd build
          cmake ..
          cmake --build .
      
      - name: Move EllipseFromOutline to desired folder
        run: |
          mv ${{ github.workspace }}/ToolBox/MeshGeneration/2DEllipse/src/build/EllipseFromOutline ${{ github.workspace }}/Toolbox/MeshGeneration/2DEllipse/

      # Install test dependencies
      - name: Install test dependencies
        run: |
          sudo apt-get update
          sudo apt-get install python3
          pip install pytest

      # Run pytest in the tests/regression directory
      - name: Run mesh generation regression tests
        run: |
          cd ${{ github.workspace }}/tests/mesh_gen_reg/
          pytest